{snippet content}
    {?
       $control->tabContainer->addClass("ui-tabs ui-widget ui-widget-content ui-corner-all");
       $control->tabContainer->id = $control->DOMtabsID;
    }
    {!$control->tabContainer->startTag()}
        {* Navigace v tabech *}
        <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
            {foreach $control->components AS $name => $tab}
                <?
                  $li = Html::el("li")->class("ui-tabs-panel ui-widget-content ui-state-default ui-corner-top");
                  if($activeTab->getName() == $name)
                      $li->addClass("ui-tabs-selected ui-state-active");
                  else
                      $li->addClass("ui-state-default");
                ?>
                {!$li->startTag()}
                    <a id="{$control->getSnippetId('a_'.$name)}" href="{link activateTab!, "activeTab"=>$name}">
                       <span>{!$tab->header}</span>
                    </a>
                {!$li->endTag()}
            {/foreach}
        </ul>

        {* Výpis obsahu tabů *}
        @{foreach $control->components AS $name => $tab}
            {* Musí se provést vždy - proto zavináč *}
            @{?
                $container = Html::el("div")->addClass("ui-tabs-panel ui-widget-content ui-corner-bottom");
                if($activeTab->getName() != $name)
                    $container->addClass("ui-tabs-hide");
            }
            {snippet $name $container}
                @{if isSet($component->tabsForDraw[$name])}
                    @{? $tab->renderContent();}
                @{/if}
            {/snippet}
        @{/foreach}
    {!$control->tabContainer->endTag()}

    @{if $control->mode !== TabControl::MODE_NO_AJAX}
        <script type="text/JavaScript">
            $(function(){
                {if is_string($control->loaderText)}
                    {foreach $control->components AS $name => $tab}
                        {if $activeTab->getName() != $name}
                            $("#"+{$control->getSnippetId($name)}).livequery(function(){
                                $(this).html({$control->loaderText});
                            });
                        {/if}
                    {/foreach}
                {/if}
                {foreach $control->components AS $name => $tab}
                        $("#"+{$control->getSnippetId('a_'.$name)}).each(function(){
                            var jThis = $(this);
                            jThis.attr("url",jThis.attr("href"));
                            jThis.attr("href","#"+{$control->getSnippetId($name)});
                            jThis.attr("loaded",false);
                            jThis.get(0).jTab = $("#"+{$control->getSnippetId($name)})
                            jThis.get(0).jTab.get(0).jAnchor = jThis;

                            {* ### MODE_PRELOAD ### *}
                            {if $control->mode == TabControl::MODE_PRELOAD}
                                {if $activeTab->getName() != $name}
                                    $.getJSON({link preload activeTab=>$name});
                                {/if}
                            {/if}
                            
                            $("#"+{$control->DOMtabsID}).bind("tabsselect",function(event,ui){
                                if(ui.panel.id === {$control->getSnippetId($name)}){
                                    var tab = $("#"+{$control->getSnippetId("a_".$name)});
                                    var panel = $("#"+{$control->getSnippetId($name)});

                                    {* ### MODE_LAZY ### *}
                                    {if $control->mode == TabControl::MODE_LAZY}
                                        if(panel.html() == {$control->loaderText}){
                                            //alert("test");
                                            $.getJSON(jThis.attr("url"));
                                            jThis.attr("loaded",1);
                                        }
                                    {/if}

                                    {* ### MODE_RELOAD ### *}
                                    {if $control->mode == TabControl::MODE_RELOAD}
                                        {if is_string($control->loaderText)}
                                            jThis.get(0).jTab.html({$control->loaderText});
                                        {/if}
                                        $.getJSON(jThis.attr("url"));
                                    {/if}
                                }
                            })
                        });
                {/foreach}

                /* Tohle by bylo fajn, ale nevím jak změnit persistentní parametr v průběhu renderování
                {if $control->mode === TabControl::MODE_PRELOAD}
                    $.getJSON({link preload!});
                {/if}
                */
                $("#"+{$control->DOMtabsID}).livequery(function(){
                    $(this).tabs({!$component->jQueryTabsOptions})
                })
            })
        </script>
        {snippet JavaScript}
            <script type="text/JavaScript">
                $(function(){
                    var tabs = $("#"+{$control->DOMtabsID})
                    {foreach $control->javaScript AS $code}
                        {!$code}
                    {/foreach}
                });
            </script>
        {/snippet}
    @{/if}
{/snippet}