<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> 
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Language" content="en">
        <meta http-equiv="Content-Script-Type" content="text/javascript">
        <meta http-equiv="Content-Style-Type" content="text/css">

	<title>TabControl - Nette Framework example</title>

	<!-- custom CSS -->
	<link rel="stylesheet" media="screen" href="http://jquery-ui.googlecode.com/svn/tags/1.7.2/themes/cupertino/ui.all.css" type="text/css">
	<link rel="stylesheet" media="screen" href="{$baseUri}css/screen.css" type="text/css">
	<link rel="stylesheet" media="screen" href="{$baseUri}css/datagrid.css" type="text/css">
	<link rel="stylesheet" media="screen" href="{$baseUri}css/ajax.css" type="text/css">
	<link rel="stylesheet" media="print" href="{$baseUri}css/print.css" type="text/css">

	<!-- jQuery -->
	<script type="text/javascript" src="http://jquery-ui.googlecode.com/svn/tags/1.7.2/jquery-1.3.2.js"></script>
	<script type="text/javascript" src="{$baseUri}js/jquery.livequery.js"></script>
	<script type="text/javascript" src="http://jquery-ui.googlecode.com/svn/tags/1.7.2/ui/ui.core.js"></script>
	<script type="text/javascript" src="http://jquery-ui.googlecode.com/svn/tags/1.7.2/ui/ui.datepicker.js"></script>
	<script type="text/javascript" src="http://jquery-ui.googlecode.com/svn/tags/1.7.2/ui/ui.sortable.js"></script>
	<script type="text/javascript" src="http://jquery-ui.googlecode.com/svn/tags/1.7.2/ui/ui.tabs.js"></script>
	<script type="text/javascript" src="http://jquery-ui.googlecode.com/svn/tags/1.7.2/ui/i18n/ui.datepicker-cs.js"></script>

	<!-- custom JS -->
	<script src="{$baseUri}js/jquery.nette.js" type="text/javascript"></script>
	<script src="{$baseUri}js/datagrid.js" type="text/javascript"></script>
</head>

<body>
	<h1>TabControl - Nette Framework example</h1>

	{snippet flashes}
	<div id="flashes">
		{foreach $flashes as $flash}
		<div class="flash {$flash->type}">{!$flash->message}</div>
		{/foreach}

		<!--
		<div class="flash info">Info message.</div>
		<div class="flash success">Success message.</div>
		<div class="flash warning">Warning message.</div>
		<div class="flash error">Error message.</div>
		<div class="flash validation">Validation message.</div>
		-->

	</div>
	{/snippet}


	<div id="mainframe-cover">
		<div id="mainframe" class="rounded">
			@{block #content}
                            No content
                        @{/block}
		</div>
	</div>
</body>
</html>
